### ISSUE TITLE
Mesh Out node

### ISSUE THREAD

**Issue by zeffii** [Sverchok/Sverchok#15] opened 2017-01-30 14:34 UTC
at the moment most of it works, but it doesn't display anything unless the input contains edges and meshes .

not sure why, haven't looked deeply.

**Comment by ly29** [comment] 2017-01-30 14:46
The problem is with system and not the mesh out node, un connected sockets get ```[None]``` instead of ```None```

**Comment by ly29** [comment] 2017-01-30 14:50
So that should be fixed, but still there is some work to do on the backend even if is mostly functional

**Closed as completed** 2017-01-30 19:47 UTC
Labels: bug
